### PR TITLE
WK of 6/1 -- New journals, API documentation

### PR DESCRIPTION
**Pull request by sjoyal**

### CODE REVIEW

**Comment by gatorpazz** [comment]
OH YEAH! NICE DESCRIPTION OF THE BOX MODEL!!! BIG PIMPIN!!!!! 6/10 :+1:

**Comment by BFGriffith** [comment]
Good basic box model concise description Sean! :+1:

**Comment by al-the-x** [comment]
Checklist here, too, please.

**Comment by al-the-x** [comment]
Great job interrogating those API docs and Wikipedia, sir! Very impressive! Did you work with someone on this?

**Comment by sjoyal** [comment]
This was all me, in an effort to even understand what an API was before trying to read the Github API docs.

**Pull request merged**
