### PR TITLE
Peeeeeas and Arrrrrtichokes journal-week-3 branch

### PR DESCRIPTION
**Pull request by sjoyal**

### CODE REVIEW

**Comment by BFGriffith** [comment]
Good draft and nice focus on vanilla JS and lodash. :+1:

**Comment by MStaehling** [comment]
Solid drafts, good example of the difference between vanilla js and jquery :+1:

**Comment by gatorpazz** [comment]
Your journal was so good it made me wanna hurl with emotion. I like the tips at the end of your reflective. Your tutorial copied mine a bit. I give your journal a 3π/10 :+1:

**Comment by pcreglow** [comment]
All good. When our blogs go live, I will be linking to that JS & JQuery tutorial. I like links so it could be helpful to see links for mentions like bower, lodash, etc. Tips for surviving week 3 is a great addition. "Tips at TIY" probably deserves it's own website?!?  Overall, :+1:

**Comment by BFGriffith** [comment]
Like the tips and your reflections on week 3 Sean. :+1:

**Comment by pope410211** [comment]
:+1:  Enjoyed the tips for survival. Though you may have wanted to adjust your in coding line there, as you had to scroll over to read all of it.

**Pull request merged**
